### PR TITLE
Bug fix #5: Navbar responsive and NavLinks

### LINKED ISSUE #5: Home Page -> Header

### PR DESCRIPTION
**Pull request by emrerdem1**
Hey Louis!

These changes will:

*Add `NavLink`s to ProfilePage and searchPreview.
*LanguageDropdown's toggle alignment.
*Adjust the responsive of `loggedInUserNavigation`.

Please let me know if you see anything poorly done.

### CODE REVIEW

File: src/components/layout/nav/Navbar.jsx [hunk 1]
```diff
@@ -214,11 +214,13 @@ const Navbar = () => {
     </Overlay>
   );
 
+  const checkUserLoggedInUi = isLoggedIn ? "userLoggedIn" : "";
```
Comment (louisrli) [inline src/components/layout/nav/Navbar.jsx]: loggedInUserClassName

**Review by louisrli — APPROVED** [review]

**Review by MiraAr — APPROVED** [review]
